[package]
name = "parse-linklist"
version = "0.1.0"
authors = ["hwc <hwc@mbp.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "*"
failure = "*"
structopt = "0.3"

